### ISSUE TITLE
Need a dynamic front page for my website

### ISSUE THREAD

**Issue by lottoxbd** [lottoxbd/frontpage#1]
I create my website.  But my front page is not so good. 

I need a cool frontpage with css and java script. 

anyone can help me by sending a cool front page

my website link is https://lottox365.com

**Comment by avantikadev** [comment]
Hi. I am @avantika. I can help you. I will upload it sometimes letter.

**Comment by avantikadev** [comment]
hi I have done your task request and uploaded it via fork

here is the file  [Link](https://github.com/avantikadev/frontpage/blob/master/frontpage%20lottox365.zip)

**Comment by avantikadev** [comment]
[frontpage lottox365.zip](https://github.com/lottoxbd/frontpage/files/2478320/frontpage.lottox365.zip)

**Comment by lottoxbd** [comment]
Thank you so much.

**Comment by lottoxbd** [comment]
I have uploaded it. Yahoo. Its very cool. Responsive and the style is so nice.
